### ISSUE TITLE
connect youtube API, gather info about every video at build time

### ISSUE THREAD

**Issue by jmg8766** [jmg8766/marketing-reschool#2]
In `gatsby-node.js` we are building a page for each video, the current context we send to each page is a channel title and a videoId. We need to refactor channels.json to contain a playlist ID instead of a list of video ids, then use the [youtube api ](https://developers.google.com/youtube/v3/getting-started) at build time to retrieve a video id, author, title, and possibly other information and pass that info in as well.

Channel Name | Link to playlist
-- | --
History of Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV3ypTVrLyZSFcT5atoUI8nl
Vintage commercials | https://www.youtube.com/playlist?list=PLrVVzxlvliV3QBS2jLc_2nZkT5tkAWuUe
Marketing stories | https://www.youtube.com/playlist?list=PLrVVzxlvliV3kDWdlP6pmBEO9fpzt_TU0
Content Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV0FsPenvdGOCuJdrYnq_LZ-
Design Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV0sqbHwNzvtKWJ7ILUh7e4G
Growth Hacking | https://www.youtube.com/playlist?list=PLrVVzxlvliV2uXjPOEcEeHwe5qLvD9Mr6
Email Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV1FirUw43IMgRaMV2D0vpwa
PPC / SEM (Paid Marketing) | https://www.youtube.com/playlist?list=PLrVVzxlvliV25VsB9ZYLoO66xwv4gdSO1
Product Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV1mFYjIueE1VFgJndNNs5Gm
B2B Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV2aiNJEVsi-hyIir5q6PGQP
B2C Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV332WCjAUb1_cSkBQ_nW0jq
ABM Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV0YS463SjdrtSKLOu56k4cM
Social Media Marketing | https://www.youtube.com/playlist?list=PLrVVzxlvliV3x0WSNFsi96BLYztd_xSAJ
Marketing ReSchool: 101 |  
VeryGoodCopy |

**Comment by Brandon-Gottshall** [comment]
I’m familiar with Axios, that part should be relatively simple. Although I already hit a snag with authentication. Apparently an API key is not sufficient for the Youtube API. Reasons:

1. Google’s API explorer gives you an error whenever you opt-out of O-auth and try to use just the api key.
2. I can’t complete a successful get request from my machine after numerous formatting attempts of the authentication header.

You have to use an OAuth flow. I’m pretty sure it’s not gonna matter who’s authenticated if I’m looking at the details of a public playlist. I’m gonna set up OAuth on my own API console and attempt to fetch the details using that.
